### ISSUE TITLE
gene_stat cpms 

### ISSUE THREAD

**Issue by AMChalkie** [LiuzLab/CB2#8] opened 2020-05-14 00:21 UTC
Hi,

I've come across a case with confusing results: 

At the gene_stat level, we sometimes get cpm_a < cpm_b, while logFC is -ve.
It's to do with the combining of the replicates, but I think it would be useful to have information on the gene level of how many probes are consistent (in this case 3 or 4, or perhaps number_sgrna_up, number_sgrna_down?   

Thanks
Alistair

Gene level:
n_sgrna    cpm_a    cpm_b     logFC 
4 10.20239 28.36188 -1.069289

sgrna level
n_a n_b       phat_a vhat_a       phat_b vhat_b     cpm_a        cpm_b     logFC 
 1   1 1.461569e-05      0 8.329479e-07      0 14.615689   0.83294789 -3.090759 
 1   1 1.686701e-05      0 1.114901e-04      0 16.867005 111.49007463  2.654428 
 1   1 5.288807e-06      0 8.329479e-08      0  5.288807   0.08329479 -2.537360 
 1   1 4.038075e-06      0 1.041185e-06      0  4.038075   1.04118486 -1.303466

**Comment by hyunhwaj** [comment] 2020-05-18 12:18
@AMChalkie thanks for the report, and our team also aware of that it is possible to have discrepancy between cpm and logFC. One of the plan is adding two modes for the logFC (averaged sgRNA-levels or directly from gene-level cpm). Regarding your `number_sgrna_up` and `number_sgrna_down`, Let me think about it. 

Thank you,

Hyun-Hwan Jeong

**Comment by hyunhwaj** [comment] 2020-05-26 09:45
Duplicate of #9

**Closed by hyunhwaj** 2020-05-26 09:45 UTC
